name: Automated scrap

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          main.py
          requirements.txt
          forwarded_messages.json
        sparse-checkout-cone-mode: false
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    
    - run: pip install -r requirements.txt
    
    - run: python main.py
      timeout-minutes: 8
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        STRING_SESSION: ${{ secrets.STRING_SESSION }}
        TOKEN: ${{ secrets.TOKEN }}
        PYTHONUNBUFFERED: "1"
      
    - run: |
        if ! git diff --quiet; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add forwarded_messages.json
          git commit -m "Update: $(date -u '+%Y-%m-%d %H:%M')"
          git push
        fi
