name: Automated scrap

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          main.py
          config.py
          requirements.txt
          forwarded_messages.json
        sparse-checkout-cone-mode: false
        fetch-depth: 1  # Only fetch latest commit
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: ~/.local/lib/python3.11/site-packages
        key: ${{ runner.os }}-python-3.11-${{ hashFiles('requirements.txt') }}
    
    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: pip install --user -r requirements.txt --no-warn-script-location --disable-pip-version-check
    
    - name: Run script
      run: python main.py
      timeout-minutes: 8  # Reduced timeout
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        STRING_SESSION: ${{ secrets.STRING_SESSION }}
        TOKEN: ${{ secrets.TOKEN }}
        PYTHONUNBUFFERED: "1"
        PYTHONDONTWRITEBYTECODE: "1"  # Skip .pyc files
      
    - name: Commit changes
      run: |
        # Check if there are changes and commit
        if ! git diff --quiet forwarded_messages.json; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add forwarded_messages.json
          git commit -m "Update db [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
